class OrdersAllFiltersConst:
    # Filters - Рахунок
    FILTERS_ACCOUNT_TITLE_TEXT = "Рахунок"
    FILTERS_ACCOUNT_TITLE_XPATH = f".//mat-label[contains(.,'{FILTERS_ACCOUNT_TITLE_TEXT}')]"
    FILTERS_ACCOUNT_XPATH = ".//input[contains(@formcontrolname,'payment_system_details')]"
    FILTERS_ACCOUNT_DETAILS_CELLS_XPATH = ".//div[@class='order__row ng-star-inserted'][contains(.,'Рахунок')]//div[@class='order__value']"

    # Filters - Назва сервісу
    FILTERS_SERV_NAME_TITLE_TEXT = "Назва сервісу"
    FILTERS_SERV_NAME_TITLE_XPATH = f".//mat-label[contains(.,'{FILTERS_SERV_NAME_TITLE_TEXT}')]"
    FILTERS_SERV_NAME_XPATH = ".//input[contains(@formcontrolname,'payment_service_name')]"
    FILTERS_SERV_NAME_CELLS_XPATH = ".//mat-cell[contains(@class,'cdk-column-payment_service_name')]"

    # Filters - Платіжна система
    FILTERS_PAY_SYS_TITLE_TEXT = "Платіжна система"
    FILTERS_PAY_SYS_TITLE_XPATH = f".//mat-label[contains(.,'{FILTERS_PAY_SYS_TITLE_TEXT}')]"
    FILTERS_PAY_SYS_XPATH = ".//mat-select[contains(@formcontrolname,'payment_system')]"
    FILTERS_PAY_SYS_BANK_TR_TEXT = "Bank Transfer"
    FILTERS_PAY_SYS_BANK_TR_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_BANK_TR_TEXT}')]"
    FILTERS_PAY_SYS_BITCOIN_TEXT = "Bitcoin"
    FILTERS_PAY_SYS_BITCOIN_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_BITCOIN_TEXT}')]"
    FILTERS_PAY_SYS_CAPITALIST_TEXT = "Capitalist"
    FILTERS_PAY_SYS_CAPITALIST_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_CAPITALIST_TEXT}')]"
    FILTERS_PAY_SYS_CARD_TEXT = "Card"
    FILTERS_PAY_SYS_CARD_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_CARD_TEXT}')]"
    FILTERS_PAY_SYS_NETELLER_TEXT = "Neteller"
    FILTERS_PAY_SYS_NETELLER_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_NETELLER_TEXT}')]"
    FILTERS_PAY_SYS_PAYPAL_TEXT = "PayPal"
    FILTERS_PAY_SYS_PAYPAL_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_PAYPAL_TEXT}')]"
    FILTERS_PAY_SYS_PAYPAL_INV_TEXT = "PayPal Invoice"
    FILTERS_PAY_SYS_PAYPAL_INV_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_PAYPAL_INV_TEXT}')]"
    FILTERS_PAY_SYS_QIWI_TEXT = "Qiwi"
    FILTERS_PAY_SYS_QIWI_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_QIWI_TEXT}')]"
    FILTERS_PAY_SYS_SKRILL_TEXT = "Skrill"
    FILTERS_PAY_SYS_SKRILL_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_SKRILL_TEXT}')]"
    FILTERS_PAY_SYS_ERC20_TEXT = "USDT ERC20"
    FILTERS_PAY_SYS_ERC20_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_ERC20_TEXT}')]"
    FILTERS_PAY_SYS_TRC20_TEXT = "USDT TRC20"
    FILTERS_PAY_SYS_TRC20_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_TRC20_TEXT}')]"
    FILTERS_PAY_SYS_WEBMONEY_TEXT = "Webmoney"
    FILTERS_PAY_SYS_WEBMONEY_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_PAY_SYS_WEBMONEY_TEXT}')]"

    # Filters - Тип замовлення
    FILTERS_ORDER_TYPE_TITLE_TEXT = "Тип замовлення"
    FILTERS_ORDER_TYPE_TITLE_XPATH = f".//mat-label[contains(.,'{FILTERS_ORDER_TYPE_TITLE_TEXT}')]"
    FILTERS_ORDER_TYPE_XPATH = ".//mat-select[contains(@formcontrolname,'order_type')]"
    FILTERS_ORDER_TYPE_LINK_TEXT = "Link"
    FILTERS_ORDER_TYPE_LINK_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_ORDER_TYPE_LINK_TEXT}')]"
    FILTERS_ORDER_TYPE_CONTENT_TEXT = "Content"
    FILTERS_ORDER_TYPE_CONTENT_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_ORDER_TYPE_CONTENT_TEXT}')]"
    FILTERS_ORDER_TYPE_OTHER_TEXT = "Other"
    FILTERS_ORDER_TYPE_OTHER_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_ORDER_TYPE_OTHER_TEXT}')]"
    FILTERS_ORDER_TYPE_CELLS_XPATH = ".//mat-cell[contains(@class,'cdk-column-order_type mat-column-order_type')]"

    # Filters - Департаменти
    FILTERS_DEPS_TITLE_TEXT = "Департаменти"
    FILTERS_DEPS_TITLE_XPATH = f".//mat-label[contains(.,'{FILTERS_DEPS_TITLE_TEXT}')]"
    FILTERS_DEPS_XPATH = ".//mat-select[contains(@formcontrolname,'departments')]"
    FILTERS_DEPS_INT_GMP_TEXT = "INT iGaming Media Project"
    FILTERS_DEPS_INT_GMP_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_DEPS_INT_GMP_TEXT}')]"
    FILTERS_DEPS_INT_PRODUCTS_TEXT = "INT Products"
    FILTERS_DEPS_INT_PRODUCTS_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_DEPS_INT_PRODUCTS_TEXT}')]"
    FILTERS_DEPS_INT_SATELLITES_TEXT = "INT Satellites"
    FILTERS_DEPS_INT_SATELLITES_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_DEPS_INT_SATELLITES_TEXT}')]"
    FILTERS_DEPS_CIS_GMP_TEXT = "CIS iGaming Media Project"
    FILTERS_DEPS_CIS_GMP_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_DEPS_CIS_GMP_TEXT}')]"
    FILTERS_DEPS_CIS_PRODUCTS_TEXT = "CIS Products"
    FILTERS_DEPS_CIS_PRODUCTS_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_DEPS_CIS_PRODUCTS_TEXT}')]"
    FILTERS_DEPS_CIS_GENERAL_TEXT = "CIS General"
    FILTERS_DEPS_CIS_GENERAL_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_DEPS_CIS_GENERAL_TEXT}')]"

    # Filters - Команди
    FILTERS_TEAMS_TITLE_TEXT = "Команди"
    FILTERS_TEAMS_TITLE_XPATH = f".//mat-label[contains(.,'{FILTERS_TEAMS_TITLE_TEXT}')]"
    FILTERS_TEAMS_XPATH = ".//mat-select[contains(@formcontrolname,'teams')]"
    FILTER_TEAMS_VALUES_LIST_XPATH = ".//mat-optgroup[@role='group']//span[@class='mdc-list-item__primary-text']"

    FILTERS_TEAMS_MEGADEPH_INT_TEXT = "MegaDeph INT"
    FILTERS_TEAMS_MEGADEPH_INT_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_MEGADEPH_INT_TEXT}')]"
    FILTERS_TEAMS_FIRST_INT_TEXT = "The_First INT"
    FILTERS_TEAMS_FIRST_INT_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_FIRST_INT_TEXT}')]"
    FILTERS_TEAMS_ALL_INT_TEXT = "All INT"
    FILTERS_TEAMS_ALL_INT_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_ALL_INT_TEXT}')]"
    FILTERS_TEAMS_MARKETING_TEXT = "Marketing"
    FILTERS_TEAMS_MARKETING_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_MARKETING_TEXT}')]"
    FILTERS_TEAMS_PL_TEXT = "PL Team"
    FILTERS_TEAMS_PL_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_PL_TEXT}')]"
    FILTERS_TEAMS_X_TEXT = "X-Team"
    FILTERS_TEAMS_X_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_X_TEXT}')]"
    FILTERS_TEAMS_CORE_TEXT = "Core Team"
    FILTERS_TEAMS_CORE_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_CORE_TEXT}')]"
    FILTERS_TEAMS_SLOTOZILLA_TEXT = "Slotozilla Team"
    FILTERS_TEAMS_SLOTOZILLA_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_SLOTOZILLA_TEXT}')]"

    FILTERS_TEAMS_PRODUCT_TEXT = "Product Team"
    FILTERS_TEAMS_PRODUCT_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_PRODUCT_TEXT}')]"
    FILTERS_TEAMS_YS_TEXT = "YS"
    FILTERS_TEAMS_YS_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_YS_TEXT}')]"

    FILTERS_TEAMS_YS_SAT_TEXT = "YS Satellites"
    FILTERS_TEAMS_YS_SAT_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_YS_SAT_TEXT}')]"
    FILTERS_TEAMS_SATELLITES_TEXT = "Satellites Team"
    FILTERS_TEAMS_SATELLITES_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_SATELLITES_TEXT}')]"

    FILTERS_TEAMS_FIRST_CIS_TEXT = "The_First CIS"
    FILTERS_TEAMS_FIRST_CIS_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_FIRST_CIS_TEXT}')]"
    FILTERS_TEAMS_MEGADEPH_CIS_TEXT = "MegaDeph CIS"
    FILTERS_TEAMS_MEGADEPH_CIS_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_MEGADEPH_CIS_TEXT}')]"
    FILTERS_TEAMS_PBN_TEXT = "PBN"
    FILTERS_TEAMS_PBN_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_PBN_TEXT}')]"
    FILTERS_TEAMS_OTHER_TEXT = "Other"
    FILTERS_TEAMS_OTHER_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_OTHER_TEXT}')]"

    FILTERS_TEAMS_TOP_SEO_TEXT = "TOP SEO"
    FILTERS_TEAMS_TOP_SEO_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_TOP_SEO_TEXT}')]"
    FILTERS_TEAMS_MULTI_SEO_TEXT = "Multi SEO"
    FILTERS_TEAMS_MULTI_SEO_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_MULTI_SEO_TEXT}')]"

    FILTERS_TEAMS_ALL_CIS_TEXT = "All CIS"
    FILTERS_TEAMS_ALL_CIS_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_ALL_CIS_TEXT}')]"
    FILTERS_TEAMS_DEV_TEXT = "Dev team"
    FILTERS_TEAMS_DEV_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_TEAMS_DEV_TEXT}')]"

    # Filters - Ким оновлено
    FILTERS_UPD_BY_XPATH = ".//mat-select[contains(@formcontrolname,'updated_by_role')]"
    FILTERS_UPD_BY_TITLE_TEXT = "Ким оновлено"
    FILTERS_UPD_BY_TITLE_XPATH = f".//mat-label[contains(.,'{FILTERS_UPD_BY_TITLE_TEXT}')]"
    FILTERS_UPD_BY_CUSTOMER_TEXT = "Замовник"
    FILTERS_UPD_BY_CUSTOMER_XPATH = f".//span[contains(@class,'mdc-list-item__primary-text')][contains(.,'{FILTERS_UPD_BY_CUSTOMER_TEXT}')]"
    FILTERS_UPD_BY_TEAM_LEAD_TEXT = "Керівник команди"
    FILTERS_UPD_BY_TEAM_LEAD_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_UPD_BY_TEAM_LEAD_TEXT}')]"
    FILTERS_UPD_BY_MODERATOR_TEXT = "Модератор"
    FILTERS_UPD_BY_MODERATOR_XPATH = f".//span[contains(@class,'mdc-list-item__primary-text')][contains(.,'{FILTERS_UPD_BY_MODERATOR_TEXT}')]"
    FILTERS_UPD_BY_ANALYST_TEXT = "Аналітик"
    FILTERS_UPD_BY_ANALYST_XPATH = f".//span[contains(@class,'mdc-list-item__primary-text')][contains(.,'{FILTERS_UPD_BY_ANALYST_TEXT}')]"
    FILTERS_UPD_BY_HEAD_DEP_TEXT = "Керівник департаменту"
    FILTERS_UPD_BY_HEAD_DEP_XPATH = f".//span[contains(@class,'mdc-list-item__primary-text')][contains(.,'{FILTERS_UPD_BY_HEAD_DEP_TEXT}')]"
    FILTERS_UPD_BY_CEO_COO_TEXT = "COO/CEO"
    FILTERS_UPD_BY_CEO_COO_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_UPD_BY_CEO_COO_TEXT}')]"
    FILTERS_UPD_BY_CELLS_XPATH = ".//mat-cell[contains(@class,'cdk-column-updated_by mat-column-updated_by')]//span[contains(@class,'grey-text')]"

    # Filters - ID замовлення
    FILTERS_ID_XPATH = ".//input[contains(@formcontrolname,'id')]"
    FILTERS_ID_TITLE_TEXT = "ID замовлення"
    FILTERS_ID_TITLE_XPATH = f".//mat-label[contains(.,'{FILTERS_ID_TITLE_TEXT}')]"
    FILTERS_ID_CELLS_XPATH = ".//mat-cell[contains(@class,'cdk-column-id')]"

    # Filters - Статус
    FILTERS_STATUS_DEFAULT_TEXT = "active"
    FILTERS_STATUS_DEFAULT_XPATH = ".//mat-select[contains(@formcontrolname,'status')]//span[contains(@class,'mat-mdc-select-min-line')]"
    FILTERS_STATUS_XPATH = ".//mat-select[contains(@formcontrolname,'status')]"
    FILTER_STATUS_LISTBOX_XPATH = ".//div[@role='listbox']//span[contains(@class,'mdc-list-item__primary-text')]"
    FILTERS_STATUS_ALL_TEXT = "all"
    FILTERS_STATUS_ALL_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_STATUS_ALL_TEXT}')]"
    FILTERS_STATUS_COMPLETED_TEXT = "completed"
    FILTERS_STATUS_COMPLETED_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_STATUS_COMPLETED_TEXT}')]"
    FILTERS_STATUS_DECLINED_TEXT = "declined"
    FILTERS_STATUS_DECLINED_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_STATUS_DECLINED_TEXT}')]"
    FILTERS_STATUS_DELETED_TEXT = "deleted"
    FILTERS_STATUS_DELETED_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_STATUS_DELETED_TEXT}')]"
    FILTERS_STATUS_PAYMENT_TEXT = "payment"
    FILTERS_STATUS_PAYMENT_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_STATUS_PAYMENT_TEXT}')]"
    FILTERS_STATUS_PREPAYMENT_TEXT = "prepayment"
    FILTERS_STATUS_PREPAYMENT_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_STATUS_PREPAYMENT_TEXT}')]"
    FILTERS_STATUS_CH_PREPAYMENT_TEXT = "checking_prepayment"
    FILTERS_STATUS_CH_PREPAYMENT_XPATH = f".//span[@class='mdc-list-item__primary-text'][contains(.,'{FILTERS_STATUS_CH_PREPAYMENT_TEXT}')]"
    FILTERS_STATUS_CELLS_XPATH = ".//mat-cell[contains(@class,'cdk-column-current_stage')]"
